server.port=8081
bff.canal=WEB
bff.issuer=urn:banco-xyz:web
bff.audience=bff-web
bff.usuario=web-demo
bff.usuario-consulta=web-consulta
bff.jwt-secret=${BFF_JWT_SECRET}
bff.token-seconds=300
bff.password=${BFF_LOGIN_PASSWORD}
bff.password-consulta=${BFF_READ_PASSWORD}
bff.cuenta-id=106
server.ssl.enabled=true
server.ssl.key-store=${BFF_TLS_STORE}
server.ssl.key-store-password=${BFF_TLS_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-tls
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.error.include-message=never
server.error.include-stacktrace=never
server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=1024
server.address=127.0.0.1

eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port=${server.port}
