server.port=8094
server.address=0.0.0.0
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bank_xyz_semana5_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:bank_batch_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.sql.init.mode=never
backend.security.usuario=${BACKEND_BASIC_USER:svc-bff}
backend.security.password=${BACKEND_BASIC_PASSWORD:ChangeMe-Semana6-Backend!}
backend.security.viewer-usuario=${BACKEND_VIEWER_USER:viewer}
backend.security.viewer-password=${BACKEND_VIEWER_PASSWORD:ChangeMe-Semana6-Viewer!}
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
