server.port=8095
server.address=0.0.0.0
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bank_xyz_semana5_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:bank_batch_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.sql.init.mode=never
backend.security.usuario=${BACKEND_BASIC_USER:svc-bff}
backend.security.password=${BACKEND_BASIC_PASSWORD:ChangeMe-Semana6-Backend!}
backend.security.viewer-usuario=${BACKEND_VIEWER_USER:viewer}
backend.security.viewer-password=${BACKEND_VIEWER_PASSWORD:ChangeMe-Semana6-Viewer!}
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.request.timeout.ms=1500
spring.kafka.producer.properties.delivery.timeout.ms=5000
spring.kafka.producer.properties.max.block.ms=2000
app.kafka.topics.pagos-procesados=pagos.procesados
app.outbox.enabled=${OUTBOX_ENABLED:true}
app.outbox.intervalo-ms=2000
app.outbox.espera-ms=7000
