spring.application.name=bank-bff-movil
spring.main.web-application-type=servlet
server.port=${BFF_MOVIL_PORT:8082}
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
logging.file.name=logs/bff-movil.log

bff.canal=MOVIL
bff.seguridad.api-key=${BFF_MOVIL_API_KEY}
