spring.application.name=bank-bff-cajero
spring.main.web-application-type=servlet
server.port=${BFF_CAJERO_PORT:8083}
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
logging.file.name=logs/bff-cajero.log

bff.canal=CAJERO
bff.seguridad.api-key=${BFF_CAJERO_API_KEY}
