spring.application.name=bank-bff-web
spring.main.web-application-type=servlet
server.port=${BFF_WEB_PORT:8081}
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
logging.file.name=logs/bff-web.log

bff.canal=WEB
bff.seguridad.api-key=${BFF_WEB_API_KEY}
